version: "3.3"
services:
  database:
    image: postgres:14.9
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"
    volumes:
      - database-data:/var/lib/postgresql/data
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "${CACHE_HOST_PORT}:${CACHE_CONTAINER_PORT}"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${CACHE_PASS}
    volumes:
      - cache-data:/data


volumes:
  database-data:
    driver: local
  cache-data:
    driver: local
